docker_repo := "bambam955/cps449"
docker_tag := "microservice2"

# List available recipes
default:
    @just --list --unsorted

# Build the containerized app
build:
    docker build -t {{docker_repo}}:{{docker_tag}} -f Dockerfile .

# Push the container to Docker Hub
push: build
    docker push {{docker_repo}}:{{docker_tag}}

# Test-run the app in Docker
dev: build
    docker run --rm -it -p 8080:8080 {{docker_repo}}:{{docker_tag}}
